DROP TABLE ITEMS IF EXISTS;

CREATE TABLE ITEMS (
    ID NUMBER(10) NOT NULL,
    ITEM_NAME VARCHAR(30),
    PRIMARY KEY (ID)
);

INSERT INTO ITEMS (ID, ITEM_NAME) VALUES (1, 'foo');
INSERT INTO ITEMS (ID, ITEM_NAME) VALUES (2, 'bar');
