DROP TABLE ITEM IF EXISTS;

CREATE TABLE ITEM (
    ID NUMBER(10) NOT NULL,
    ITEM_NAME VARCHAR(30),
    PRIMARY KEY (ID)
);

INSERT INTO ITEM (ID, ITEM_NAME) VALUES (1, 'foo');
INSERT INTO ITEM (ID, ITEM_NAME) VALUES (2, 'bar');
